matrix:
  include:
    - language: java
      jdk:
        - oraclejdk8
      script:
        - cd java
        - mvn install -B -V
    - language: node_js
      node_js:
        - "lts/*"
      before_install:
        - cd ui/api-client/packages/sdk
