matrix:
  include:
    - language: java
      jdk:
        - oraclejdk8
      script:
        - cd java
        - mvn install -B -V
    - language: node_js
      node_js:
        - "lts/*"
      before_install:
        - cd ui/api-client/packages/sdk
      before_script:
        - yarn run build
      deploy:
        provider: script
        script: cp $TRAVIS_BUILD_DIR/.npmrc.dist $TRAVIS_BUILD_DIR/.npmrc && npm publish dist --access public --dry-run
